# Generated by Django 5.1.3 on 2024-12-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_choices',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Science Fiction (Sci-Fi)', 'Science Fiction (Sci-Fi)'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Animation', 'Animation'), ('Documentary', 'Documentary'), ('Family', 'Family'), ('Musical', 'Musical'), ('Crime', 'Crime'), ('Other Genres', 'Other Genres')], default='Other Genres', max_length=50),
        ),
    ]
